import {
  boolean,
  doublePrecision,
  integer,
  pgSequence,
  pgTable,
  primaryKey,
  serial,
  text,
  timestamp,
  uuid,
} from "drizzle-orm/pg-core";

/**
 * Raw WANDS products, loaded 1:1 from product.csv. Postgres is the system
 * of record (D10); Elasticsearch indexes are always rebuildable from here.
 * Numeric stats stay double precision to mirror the float-formatted source.
 */
export const productsRaw = pgTable("products_raw", {
  productId: integer("product_id").primaryKey(),
  name: text("name").notNull(),
  productClass: text("product_class"),
  categoryHierarchy: text("category_hierarchy"),
  description: text("description"),
  features: text("features"),
  ratingCount: doublePrecision("rating_count"),
  averageRating: doublePrecision("average_rating"),
  reviewCount: doublePrecision("review_count"),
});

/**
 * The curated ~800-product storefront catalog (D7): a selected subset of
 * products_raw mapped onto NORDHEM's own categories, with deterministic
 * synthetic prices (WANDS ships no prices — see DECISIONS). Rebuilt by
 * tools' curate-shop; re-curation cascades image assignments away.
 */
export const shopProducts = pgTable("shop_products", {
  productId: integer("product_id")
    .primaryKey()
    .references(() => productsRaw.productId),
  slug: text("slug").notNull().unique(),
  category: text("category").notNull(),
  priceCents: integer("price_cents").notNull(),
});

/** One assigned photo per shop product, hotlinked with credit (D8). */
export const productImages = pgTable("product_images", {
  productId: integer("product_id")
    .primaryKey()
    .references(() => shopProducts.productId, { onDelete: "cascade" }),
  url: text("url").notNull(),
  thumbUrl: text("thumb_url").notNull(),
  photographerName: text("photographer_name").notNull(),
  photographerUrl: text("photographer_url").notNull(),
  source: text("source").notNull(),
  searchQuery: text("search_query").notNull(),
  status: text("status").notNull().default("auto"),
});

// ---------------------------------------------------------------------------
// Better Auth core tables (D42). Shape is dictated by Better Auth's own model
// (`getAuthTables`): table + field names must match what the Drizzle adapter
// looks up. We keep the project's snake_case DB columns — the adapter reads by
// the JS property key (camelCase), so `emailVerified` maps to `email_verified`
// with no drift. Generated by inspecting Better Auth, not hand-guessed; do not
// rename keys. `user` is a reserved word in Postgres, so Drizzle quotes it.
// ---------------------------------------------------------------------------

/** A registered shopper. Better Auth owns the string `id` and timestamps. */
export const user = pgTable("user", {
  id: text("id").primaryKey(),
  name: text("name").notNull(),
  email: text("email").notNull().unique(),
  emailVerified: boolean("email_verified").notNull().default(false),
  image: text("image"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/** An active login session (cookie-backed token). Cascades with the user. */
export const session = pgTable("session", {
  id: text("id").primaryKey(),
  expiresAt: timestamp("expires_at").notNull(),
  token: text("token").notNull().unique(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
  ipAddress: text("ip_address"),
  userAgent: text("user_agent"),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
});

/**
 * A credential for a user: either email+password (the `password` hash lives
 * here, never on `user`) or a social provider link (Google). Cascades.
 */
export const account = pgTable("account", {
  id: text("id").primaryKey(),
  accountId: text("account_id").notNull(),
  providerId: text("provider_id").notNull(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  idToken: text("id_token"),
  accessTokenExpiresAt: timestamp("access_token_expires_at"),
  refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
  scope: text("scope"),
  password: text("password"),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/** Short-lived tokens for email verification / password reset flows. */
export const verification = pgTable("verification", {
  id: text("id").primaryKey(),
  identifier: text("identifier").notNull(),
  value: text("value").notNull(),
  expiresAt: timestamp("expires_at").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/** All candidate photos fetched per search query — the studio swap pool. */
export const photoPool = pgTable("photo_pool", {
  id: serial("id").primaryKey(),
  searchQuery: text("search_query").notNull(),
  url: text("url").notNull(),
  thumbUrl: text("thumb_url").notNull(),
  photographerName: text("photographer_name").notNull(),
  photographerUrl: text("photographer_url").notNull(),
  source: text("source").notNull(),
});

// ---------------------------------------------------------------------------
// Step 5 commerce tables (D43, D44).
// ---------------------------------------------------------------------------

/**
 * A shopping cart. A guest cart has a null userId and is found by the
 * `cart_id` cookie (D43); a logged-in cart sets userId. `userId` is unique
 * (nullable), which lets Postgres hold many guest carts — NULLs are distinct —
 * while enforcing exactly one cart per registered user. Merge-on-login moves
 * the guest cart's items in and deletes the guest row.
 */
export const cart = pgTable("cart", {
  id: uuid("id").primaryKey().defaultRandom(),
  userId: text("user_id")
    .unique()
    .references(() => user.id, { onDelete: "cascade" }),
  createdAt: timestamp("created_at").notNull().defaultNow(),
  updatedAt: timestamp("updated_at").notNull().defaultNow(),
});

/**
 * A line in a cart. Composite pk (cartId, productId) makes "the same product
 * is one line" a database invariant and is the upsert target when quantity is
 * bumped. No price column: the cart always reflects the live shop price; price
 * is only frozen into an order at checkout.
 */
export const cartItems = pgTable(
  "cart_items",
  {
    cartId: uuid("cart_id")
      .notNull()
      .references(() => cart.id, { onDelete: "cascade" }),
    productId: integer("product_id")
      .notNull()
      .references(() => shopProducts.productId, { onDelete: "cascade" }),
    quantity: integer("quantity").notNull(),
  },
  (t) => [primaryKey({ columns: [t.cartId, t.productId] })],
);

/** Backs the human-readable order number NDH-2026-000123 (D43). */
export const orderNumberSeq = pgSequence("order_number_seq", { startWith: 1 });

/**
 * A placed order. uuid internal pk; `orderNumber` is the human-facing
 * NDH-YYYY-NNNNNN drawn from order_number_seq at checkout. Totals are frozen
 * in cents. Demo checkout, so a single 'paid' status is enough for now.
 */
export const orders = pgTable("orders", {
  id: uuid("id").primaryKey().defaultRandom(),
  orderNumber: text("order_number").notNull().unique(),
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  status: text("status").notNull().default("paid"),
  shipFullName: text("ship_full_name").notNull(),
  shipLine1: text("ship_line1").notNull(),
  shipLine2: text("ship_line2"),
  shipCity: text("ship_city").notNull(),
  shipPostalCode: text("ship_postal_code").notNull(),
  shipCountry: text("ship_country").notNull(),
  subtotalCents: integer("subtotal_cents").notNull(),
  shippingCents: integer("shipping_cents").notNull(),
  totalCents: integer("total_cents").notNull(),
  createdAt: timestamp("created_at").notNull().defaultNow(),
});

/**
 * A frozen line of an order. productId is a plain integer (not an FK): order
 * history must survive a product being decurated, and must NEVER re-derive
 * name/price from the live catalog — everything needed to render the line is
 * snapshotted here at checkout (D44).
 */
export const orderItems = pgTable("order_items", {
  id: serial("id").primaryKey(),
  orderId: uuid("order_id")
    .notNull()
    .references(() => orders.id, { onDelete: "cascade" }),
  productId: integer("product_id").notNull(),
  nameSnapshot: text("name_snapshot").notNull(),
  slugSnapshot: text("slug_snapshot").notNull(),
  imageUrlSnapshot: text("image_url_snapshot"),
  unitPriceCents: integer("unit_price_cents").notNull(),
  quantity: integer("quantity").notNull(),
});

/**
 * A user's favorited product (the jysk.dk "Favoritter" model). Favorites
 * require login (D43), so there is no guest table. Composite pk makes a
 * favorite idempotent per user; both sides cascade.
 */
export const favorites = pgTable(
  "favorites",
  {
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    productId: integer("product_id")
      .notNull()
      .references(() => shopProducts.productId, { onDelete: "cascade" }),
    createdAt: timestamp("created_at").notNull().defaultNow(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.productId] })],
);
